# Generated by Django 3.0.8 on 2020-07-06 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='when_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
